version: "3.8"

services:
  fastapi_app:
    build:
      context: ./fastapi_app
    container_name: fastapi_app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "8000:80"
    networks:
      - mqtt_net

  mqtt_broker:
    image: eclipse-mosquitto:2.0
    container_name: mqtt_broker
    ports:
      - "1884:1884"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - mqtt_net

  mqtt_publisher:
    build:
      context: ./mqtt_publisher
    container_name: mqtt_publisher
    environment:
      - MQTT_BROKER=mqtt_broker
      - MQTT_PORT=1884
      - MQTT_TOPIC=test/etap3
    depends_on:
      - mqtt_broker
    networks:
      - mqtt_net

  mqtt_subscriber:
    build:
      context: ./mqtt_subscriber
    container_name: mqtt_subscriber
    environment:
      - MQTT_BROKER=mqtt_broker
      - MQTT_PORT=1884
      - MQTT_TOPIC=test/etap3
      - FASTAPI_HOST=fastapi_app
      - FASTAPI_PORT=80
      - FASTAPI_ENDPOINT=/items
    depends_on:
      - fastapi_app
      - mqtt_broker
    networks:
      - mqtt_net

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - mqtt_net

networks:
  mqtt_net:
    driver: bridge
