cluster.name: "airline-project-cluster"
network.host: 0.0.0.0

# Disable security features for local development
xpack.security.enabled: false
xpack.security.enrollment.enabled: false
xpack.security.http.ssl.enabled: false
xpack.security.transport.ssl.enabled: false 